aprog: main.cpp car_t.o private_t.o bus_t.o
	g++ main.cpp car_t.o private_t.o bus_t.o

car_t.o: car_t.cpp car_t.h
	g++ -c car_t.cpp car_t.h

private_t.o: private_t.cpp private_t.h
	g++ -c private_t.cpp

bus_t.o: bus_t.cpp bus_t.h
	g++ -c bus_t.cpp